# Site
repository: mahdi-mahjouri/resume-theme
favicon: images/favicon_io/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mahdi Mahjouri Namin
title: Electrical and Electronics Engineer
email: m.mahjouri1381@gmail.com
website: https://mahdi-mahjouri.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: mahdi-mahjouri
linkedin_username: mahdi-mahjouri-namin81

# Additional icon links
# additional_links:
#   - title: Resume (PDF)
#     icon: fas fa-file-pdf
#     url: /CV_Mahjouri_Dec8.pdf

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I'm Mahdi Mahjouri Namin, a senior Electrical and Electronics Engineering student at Amirkabir University of Technology (Tehran Polytechnic).  
  My main interests are in **circuit design**, **embedded systems**, **AI**, and **signal & image processing**.  
  I'm experienced in both hardware-level design (using VHDL, Verilog, Altium Designer, and Cadence tools) and software-level applications (OpenCV, PyTorch, STM32 programming).  
  Currently, I am developing AI-based systems to support diagnosis using medical imaging and contributing to real-time vehicle classification and object detection projects.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Medical Image-Based Disease Detection
        quote: >
          A deep learning-based system to improve diagnosis in colonoscopy imaging.
        description: |
          Bachelor's thesis under the supervision of Prof. Sharifian. Using YOLO-based models to enhance detection accuracy.

      - layout: top-middle
        title: Real-time Vehicle Detection & Tracking
        additional_links:
          - title: GSN Pars Co.
            icon: fas fa-industry
        quote: >
          ITS-based solution using deep learning for smart classification and tracking.
        description: |
          Internship at GSN Pars Co. (AIMS Control), working on real-time computer vision models for traffic systems.

      - layout: top-middle
        title: MIPS Single Cycle & Pipeline
        quote: >
          Designed full datapath and control in Verilog.
        description: |
          Implemented instruction set, handled hazards, and simulated performance.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Amirkabir University of Technology (Tehran Polytechnic)
        caption: 2021 – Present
        sub_title: B.Sc. in Electrical Engineering (Electronics)
        quote: >
          GPA: 17.62/20 – Ranked among top 15% of B.Sc. students.
        description: |
          Relevant coursework includes: VLSI Design, Digital Systems, Signal Processing, Embedded Systems, and AI Applications.

  - title: A Little More About Me
    layout: text
    content: |
      My technical stack includes:
      - Python, MATLAB, Verilog/VHDL, C
      - Altium Designer, Cadence Virtuoso, Vivado, Keil, STM32, Arduino, SPICE
      - TensorFlow, PyTorch, OpenCV
      - LaTeX, Git, HTML

      I enjoy solving engineering problems, working on cross-disciplinary projects, and exploring ways AI can enhance traditional hardware systems.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
